import{a as S,S as q,i as a}from"./assets/vendor-D3wb2o5V.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function y(s,t,o){const{data:i}=await S.get("https://pixabay.com/api/",{params:{key:"49218943-825793be7dcf8f9e924089ba3",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:o}});return{hits:i.hits,totalHits:i.totalHits}}const m=document.getElementById("loader"),A=document.getElementById("gallery"),p=document.getElementById("load-button"),h=document.getElementById("loading-message");async function f(s){const t=s.map(({webformatURL:o,largeImageURL:i,tags:e,likes:r,views:l,comments:I,downloads:R})=>`
          <li class="gallery-item">
            <div class="loader" id="loader" style="display: block"></div>
            <a href="${i}">
              <img src="${o}" alt="${e}"/>
              <div class="info">
                <p><b>Likes:</b> ${r}</p>
                <p><b>Views:</b> ${l}</p>
                <p><b>Comments:</b> ${I}</p>
                <p><b>Downloads:</b> ${R}</p>
              </div>
            </a>
          </li>`).join("");A.insertAdjacentHTML("beforeend",t),P()}function P(){document.querySelectorAll(".gallery-item img").forEach(t=>{const o=t.closest(".gallery-item").querySelector(".loader");o&&(o.style.display="none")})}function b(){m.style.display="block"}function c(){m.style.display="none"}function E(){p.style.display="block"}function L(){p.style.display="none"}function w(){h.style.display="block"}function d(){h.style.display="none"}function g(){const{height:s}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}const $=document.getElementById("search-form"),H=document.getElementById("load-button"),M=document.getElementById("gallery");let B,n=1;const u=15;let v=new q(".gallery a",{captionsData:"alt",captionDelay:250});$.addEventListener("submit",async s=>{s.preventDefault(),M.innerHTML="",n=1,L();const t=s.target.elements.searchQuery.value.trim();if(B=t,!t){a.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}b(),w();try{const{hits:o,totalHits:i}=await y(t,n,u),e=o,r=i;e.length===0?a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(E(),f(e),v.refresh())}catch{a.error({title:"Error",message:"An error occurred while fetching images",position:"topRight"})}finally{c(),d()}});H.addEventListener("click",async s=>{s.preventDefault(),L(),w();const t=B;if(!t){a.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}b();try{n+=1;const{hits:o,totalHits:i}=await y(t,n,u),e=o,r=i;if(e.length===0&&n===1)a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{if(n*u>=r){c(),d(),g(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}E(),f(e),v.refresh()}}catch{a.error({title:"Error",message:"An error occurred while fetching images",position:"topRight"})}finally{c(),d(),g()}});
//# sourceMappingURL=index.js.map
