import{a as R,S,i as a}from"./assets/vendor-D3wb2o5V.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();async function g(s,t,r){const{data:i}=await R.get("https://pixabay.com/api/",{params:{key:"49218943-825793be7dcf8f9e924089ba3",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}});return{hits:i.hits,totalHits:i.totalHits}}const u=document.getElementById("loader"),q=document.getElementById("gallery"),y=document.getElementById("load-button"),m=document.getElementById("loading-message");async function p(s){const t=s.map(({webformatURL:r,largeImageURL:i,tags:e,likes:o,views:n,comments:v,downloads:I})=>`
          <li class="gallery-item">
            <div class="loader" id="loader" style="display: block"></div>
            <a href="${i}">
              <img src="${r}" alt="${e}"/>
              <div class="info">
                <p><b>Likes:</b> ${o}</p>
                <p><b>Views:</b> ${n}</p>
                <p><b>Comments:</b> ${v}</p>
                <p><b>Downloads:</b> ${I}</p>
              </div>
            </a>
          </li>`).join("");q.insertAdjacentHTML("beforeend",t),A()}function A(){document.querySelectorAll(".gallery-item img").forEach(t=>{const r=t.closest(".gallery-item").querySelector(".loader");r&&(r.style.display="none")})}function h(){u.style.display="block"}function f(){u.style.display="none"}function b(){y.style.display="block"}function c(){y.style.display="none"}function E(){m.style.display="block"}function L(){m.style.display="none"}function P(){const{height:s}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}const $=document.getElementById("search-form"),H=document.getElementById("load-button"),M=document.getElementById("gallery");let w,l=1;const d=15;let B=new S(".gallery a",{captionsData:"alt",captionDelay:250});$.addEventListener("submit",async s=>{s.preventDefault(),M.innerHTML="",c();const t=s.target.elements.searchQuery.value.trim();if(w=t,!t){a.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}h(),E();try{const{hits:r,totalHits:i}=await g(t,l,d),e=r,o=i;e.length===0?a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(b(),p(e),B.refresh())}catch{a.error({title:"Error",message:"An error occurred while fetching images",position:"topRight"})}finally{f(),L()}});H.addEventListener("click",async s=>{s.preventDefault(),c(),E();const t=w;if(!t){a.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}h();try{l+=1;const{hits:r,totalHits:i}=await g(t,l,d),e=r,o=i;e.length===0&&l===1?a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(b(),p(e),B.refresh(),l*d>=o&&(c(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})))}catch{a.error({title:"Error",message:"An error occurred while fetching images",position:"topRight"})}finally{f(),L(),P()}});
//# sourceMappingURL=index.js.map
